# Project information
site_name: ML101
site_url: https://github.mskcc.org/pages/aiml/ml101/

# Repo
repo_name: ml101
repo_url: https://github.mskcc.org/aiml/ml101
edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About the training: index.md
  - Training:
    # - Introduction to ML: introduction-to-ml.md
    # - CP4D Overview: introduction-to-cp4d.md
    - Predict incident resolution time with AutoAI:      
      - About the data set: servicenow-dataset.md
      - Data processing with Data Refinery: data-refinery.md
      - AutoAI experiment: autoai.md
      - Deploying and consuming models: wml.md
    - Unstructured Data Analysis on RStudio: unstructured-data-analysis-on-rstudio.md
    - Predict incident resolution time with Watson Studio Jupyter notebooks: custom-model-deployment.md
  - Training Resources:
    - Resources: resources.md

# Theme
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: blue
    accent: blue
  logo: logo.svg
