name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: yum install rh-python36
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy
